### ISSUE TITLE
Clean the unwanted files and directories

### ISSUE THREAD

**Issue by KrutikaBhatt** [CSI-KJSCE/csi_superhero_fanpage#2]
We have simply taken the base React files to create the website. Some of the files are not used and won;t be used further like ``` setuptestVitals.js ``` ,etc . Clean the codes, put comments and remove unnecessary files

**Comment by VinayKanase** [comment]
I would like to take on this issue

**Comment by Algeo3603** [comment]
@KrutikaBhatt  I have spotted some files that are not arranged properly. Can you assign assign this to me so I can arrange them in the correct directories?
