### ISSUE TITLE
Optimize Readme to assist first time users

### ISSUE THREAD

**Issue by nishant42491** [CSI-KJSCE/csi_superhero_fanpage#3]
- -Help style a better UI.<br>

For Example <br>
<hr>

`# CSI Superhero Fanpage
The Superhero fanpage!! Create Pull request and start with open source

## Setup
```sh
$ git clone https://github.com/csikjsce/superhero-fanpage-hacktoberfest2021
$ npm install
$ npm start
```

## Starting the frontend Application
```sh
$ cd frontend_application
$ npm install
$ npm start
```
<br>
<center><h3>View the already done deployments</h3>
<b>The Frontend Application : https://krutikabhatt.github.io/superhero-fanpage-hacktoberfest2021/</b><br><br>
<b>The Node JS application : https://superherobackend12.herokuapp.com/</b>
</center>`
<br>
<hr>
<br>

- -Add Documentation about the exact workings of the frontend and backend used for a react application.<br>
- -Add more information that might assist new beginners

**Comment by charmeemehta01** [comment]
I would like to work on this issue
