### ISSUE TITLE
Add responsiveness to the home page 

### ISSUE THREAD

**Issue by sauravshetty473** [CSI-KJSCE/csi_superhero_fanpage#4]
### Basic

- Find the folder `App.css` .

- Locate the class for which the css is to be added/changed .

- Edit the css and/or add css for different media sizes .

### Expected changes
```
@media only screen and (max-width: 768px) { 
   css data for this media size .
}
```

**Comment by Algeo3603** [comment]
Could you please elaborate on what is to be done here? I would like to try contibuting to this.

**Comment by oneamanish** [comment]
see my pull req.
