### ISSUE TITLE
Change the font of web page

### ISSUE THREAD

**Issue by aayush18602** [CSI-KJSCE/csi_superhero_fanpage#5]
Our _**Superhero Fanpage**_ needs some changes in its fonts.

**Expected Changes :**

- Use different fonts and choose one of them to enhance the look when someone is seeing the Webpage
- You may change the font size but it must not affect the styling of other elements

**Comment by charmeemehta01** [comment]
Yes, I had forgotten to upload the edited .css file. I've committed the same. Is it visible now?
