### ISSUE TITLE
Adding the data as json format for CSI members

### ISSUE THREAD

**Issue by KrutikaBhatt** [CSI-KJSCE/csi_superhero_fanpage#7]
Json data can be previewed in data folder

**Comment by aayush18602** [comment]
I would like to take this Issue!!

**Comment by KrutikaBhatt** [comment]
> I would like to take this Issue!!

Yeah sure, go ahead

**Comment by nishant42491** [comment]
I would like to work on that

**Comment by KrutikaBhatt** [comment]
> I would like to work on that

Yes sure
